# Generated by extendr: Do not edit by hand
# nolint start

#' @keywords internal
#' @useDynLib calamineR, .registration = TRUE
"_PACKAGE"

#' Get sheet names from an Excel file
#' @param path Path to the Excel file
#' @return Character vector of sheet names
#' @export
cal_sheet_names <- function(path) {
  .Call(wrap__cal_sheet_names, path)
}

#' Read a sheet from an Excel file as a list of rows
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return List of character vectors (rows)
#' @export
cal_read_sheet <- function(path, sheet) {
  .Call(wrap__cal_read_sheet, path, sheet)
}

#' Read a sheet as a data.frame
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @param col_names Use first row as column names
#' @param skip Number of rows to skip before reading
#' @param fill_merged Fill merged cells with the top-left value
#' @return A data.frame
#' @export
cal_read_sheet_df <- function(path, sheet, col_names, skip, fill_merged) {
  .Call(wrap__cal_read_sheet_df, path, sheet, col_names, skip, fill_merged)
}

#' Read sheet dimensions (rows, cols)
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return Integer vector c(nrow, ncol)
#' @export
cal_sheet_dims <- function(path, sheet) {
  .Call(wrap__cal_sheet_dims, path, sheet)
}

#' Get merged cell regions from an Excel file
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return A data.frame with columns: start_row, start_col, end_row, end_col (1-based)
#' @export
cal_merge_regions <- function(path, sheet) {
  .Call(wrap__cal_merge_regions, path, sheet)
}

#' Get sheet metadata (name, type, visibility) from an Excel file
#' @param path Path to the Excel file
#' @return A data.frame with columns: name, type, visible
#' @export
cal_sheets_metadata <- function(path) {
  .Call(wrap__cal_sheets_metadata, path)
}

#' Check if a sheet is a worksheet (not a chart/dialog/macro sheet)
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return Logical: TRUE if worksheet, FALSE otherwise
#' @export
cal_is_worksheet <- function(path, sheet) {
  .Call(wrap__cal_is_worksheet, path, sheet)
}

# nolint end
