# Generated by extendr: Do not edit by hand
# nolint start

#' @keywords internal
#' @useDynLib calaminer, .registration = TRUE
"_PACKAGE"

#' Get sheet names from an Excel file
#' @param path Path to the Excel file
#' @return Character vector of sheet names
#' @export
cal_sheet_names <- function(path) {
  .Call(wrap__cal_sheet_names, path)
}

#' Read a sheet from an Excel file as a list of rows
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return List of character vectors (rows)
#' @export
cal_read_sheet <- function(path, sheet) {
  .Call(wrap__cal_read_sheet, path, sheet)
}

#' Read a sheet as a data.frame
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @param col_names Use first row as column names
#' @param skip Number of rows to skip before reading
#' @return A data.frame
#' @export
cal_read_sheet_df <- function(path, sheet, col_names, skip) {
  .Call(wrap__cal_read_sheet_df, path, sheet, col_names, skip)
}

#' Read sheet dimensions (rows, cols)
#' @param path Path to the Excel file
#' @param sheet Sheet name or index (1-based)
#' @return Integer vector c(nrow, ncol)
#' @export
cal_sheet_dims <- function(path, sheet) {
  .Call(wrap__cal_sheet_dims, path, sheet)
}

# nolint end
